### PR TITLE
pull request for makefont utility fix and html-form-guide.com captcha decoder

### PR DESCRIPTION
**Pull request by jimmikaelkael**

### CODE REVIEW

**Comment by iveney** [comment]
I got Seg fault when running on the htmlguide images. 

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000b12a50
0x00007fff87ffa120 in strlen ()
```

Could you verify this?
My gcc: i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5664)
Running Snow Leopard 10.6.7.
Other form of captcha decoders run fine in my machine.

Also, I think it is better to separate the test data from the source codes. 
Maybe we can create another repo for it.

**Comment by jimmikaelkael** [comment]
Well on my side it seems fine, tought I'm running it on Ubuntu 11.04 with gcc-4.5.2

<pre><code>jimmikaelkael@PC-DE-JIM:~/projects/pwntcha$ gdb pwntcha
GNU gdb (Ubuntu/Linaro 7.2-1ubuntu11) 7.2
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/jimmikaelkael/projects/pwntcha/pwntcha...done.
(gdb) run testsuite/htmlformguide/htmlformguide_000.jpg
Starting program: /home/jimmikaelkael/projects/pwntcha/pwntcha testsuite/htmlformguide/htmlformguide_000.jpg
[Thread debugging using libthread_db enabled]
/home/jimmikaelkael/projects/pwntcha/pwntcha: image size 120x40, 200 colours
/home/jimmikaelkael/projects/pwntcha/pwntcha: probably a htmlformguide captcha
f33gp3

Program exited normally.
(gdb)</code></pre>


Any chance you can test it too with GDB ? This could help to locate the problem with more precision.

**Comment by iveney** [comment]
Hi, the output I gave is produced by the GDB.
I backtrace and found: 

```
(gdb) bt
#0  0x00007fff87ffa120 in strlen ()
#1  0x00007fff8807d339 in puts ()
#2  0x0000000100001032 in main (argc=4, argv=0x7fff5fbfef78) at main.c:262

(gdb) p result
$1 = 0x100b12a30 "f33gp3"
```

I suspect it is because 64b issue.
Since the address of result is `0x0000000100b12a50`, but some how
strlen uses `0x0000000000b12a50`. I breakpoint at the `printf` and found that `result` is in 32b:

```
(gdb) p result
$4 = 0xb12a50 <Address 0xb12a50 out of bounds>
```

For other decoders, the `result` is in 64b and it is correct.
Can you investigate this? Thanks.

**Comment by jimmikaelkael** [comment]
Well thank you very much for the provided backtrace! Now the problem is obvious.

The Problem is that I forgot to add a prototype for decoder_htmlformguide() function in the common.h header file.
If there is no prototype and the function definition the function is used without declaration and the default declaration of C will be used, i.e. all parameter and return value will be considered as int (so 32bit).

Well, I see that some other decoders don't have a prototype, they should trigger a segfault as well.
I'm fixing this ASAP, as well as separating  testsuite and I'll update the pull request.

Thank you!

Best regards,
Jimmi.

**Comment by iveney** [comment]
Hi jimmi,
Thanks for the quick fix! I tested and it runs well now. 
Could you rebase on my master (probably create a branch for this pull) 
and cherry-pick commits without including the testsuite and revert commits? 
Just want to make the master branch clean. Thanks!

**Comment by jimmikaelkael** [comment]
now obsolete.

**Pull request closed without merging**
