### PR TITLE
new decoder for MovableType, and improvements.

### PR DESCRIPTION
**Pull request by jimmikaelkael**

### CODE REVIEW

**Comment by iveney** [comment]
Hi Jimmi,
Could you separate these commits as different pull requests?
I think each pull request should solve exactly one thing. 
Also, remember to rebase the commits on the most updated master before issuing a pull request.
Thanks.

**Comment by iveney** [comment]
I checked the commit for movable type using the data in testsuite, but the success rate is 0% ...
Paypal is 100% correct.

**Comment by jimmikaelkael** [comment]
About movabletype captchas: this sounds strange. I tested again with a fresh cloned repo and still get a 97%.
Maybe it's because input images are PNG ?

Could you please try with this patch applied on my latest commit ?

<pre>
<code>diff --git a/src/movabletype/decoder.c b/src/movabletype/decoder.c
index be9c013..d50fe5f 100644
--- a/src/movabletype/decoder.c
+++ b/src/movabletype/decoder.c
@@ -93,6 +93,8 @@ char *decode_movabletype(struct image *img)
 
     find_glyphs(tmp);
 
+    image_save(tmp, "output.bmp");
+
     image_free(tmp);
 
     return result;
@@ -156,7 +158,7 @@ static void find_glyphs(struct image *img)
         }
 
         /* Print min glyph */
-#if 0
+//#if 0
         xmin = font->glyphs[bestch].xmin - DELTA;
         ymin = font->glyphs[bestch].ymin;
         xmax = font->glyphs[bestch].xmax + DELTA;
@@ -172,7 +174,9 @@ static void find_glyphs(struct image *img)
                 }
                 setpixel(img, bestx + x, y, r, g, b);
             }
-#endif
+//#endif
+
+        image_save(img, "debug.bmp");
 
         startx = bestx + font->glyphs[bestch].xmax - font->glyphs[bestch].xmin;
         result[cur++] = font->glyphs[bestch].c;
</code></pre>


Once applied, please try to decode movabletype_000.png, it will save "output.bmp" which is the image after preprocessing, and "debug.bmp" which is is image with superimposed found glyphs.

**Comment by iveney** [comment]
Hi Jimmi,
Sorry for my late reply, I just came back from a trip.
I tried this patch, but the result is still incorrect.
See the result here: http://d.pr/G5gS
Strange enough, the output doesn't look like the original pic at all.

**Comment by jimmikaelkael** [comment]
Hi Ivan,
No problem, I hope you enjoyed your trip!

Yeah doesn't look the same, have you tried with the script or putting the command in a terminal yourself ?
Just to clarify things, could you confirm linux_fr captcha decoder works for you ? (it uses png too)

Here's another patch for you test on my latest pwntcha fork revision, this one save 7 different output bitmap in order to locate the problem.

<pre><code>diff --git a/src/movabletype/decoder.c b/src/movabletype/decoder.c
index be9c013..731f062 100644
--- a/src/movabletype/decoder.c
+++ b/src/movabletype/decoder.c
@@ -35,6 +35,7 @@ char *decode_movabletype(struct image *img)
     strcpy(result, "      ");
 
     tmp = image_dup(img);
+    image_save(tmp, "output00.bmp");
 
     /* further cleaning */
     int x, y, z, r, g, b;
@@ -71,8 +72,11 @@ char *decode_movabletype(struct image *img)
         filter_black_stuff(tmp);
     }
 
+    image_save(tmp, "output01.bmp");
     filter_median(tmp);
+    image_save(tmp, "output02.bmp");
     filter_black_stuff(tmp);
+    image_save(tmp, "output03.bmp");
 
     for(y = 0; y < tmp->height; y++)
     {
@@ -88,8 +92,11 @@ char *decode_movabletype(struct image *img)
     
     }
 
+    image_save(tmp, "output04.bmp");
     filter_black_stuff(tmp);
+    image_save(tmp, "output05.bmp");
     filter_fill_holes(tmp);
+    image_save(tmp, "output06.bmp");
 
     find_glyphs(tmp);
 
</code></pre>

**Pull request merged**
